### PR TITLE
Improve build tool

### LINKED ISSUE #22: Improve build process
At the moment we build all containers within the build and push job. However, nothing changes in most of the containers and they need a lot of time to be build. Therefore this task should split up the Pipline in two new piplines. One pipline build the "base container" like "oscm-maildev", "oscm-identity" and so on. The second pipline should only build the container which are changing frequently like "oscm-core" or "oscm-app". 

**Acceptance criteria**
- [ ] Build core pipline
- [ ] Build oscm pipline
- [ ] The build and push is still successful

### LINKED ISSUE #23: Improve build
At the moment we build all containers within the build and push core and base job. However, we are building containers with tools which are never chaning. Therefore, this tools should be build within a seperate pipline. 

Acceptance criteria

Build core pipline [ ]
Build oscm pipline [ ]
The build and push is still successful [ ]

### PR DESCRIPTION
**Pull request by cworf91**
create base job
create core job
create tool job

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/26)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/26)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @cworf91 and @GoebelL)

___
*[build-base-and-push.groovy, line 88 at r1](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/26#-MLr_NjZ41MocESJhCoA:-MLr_NjZ41MocESJhCoB:bxlcxlu) ([raw file](https://github.com/servicecatalog/oscm-jenkinsscripts/blob/95122cfa0b3e37663ca917b9441dcb2655124ef0/build-base-and-push.groovy#L88)):*
> ```Groovy
>     def push = evaluate readTrusted('shared/push-base-and-core.groovy')
>     
>     def IMAGES="db initdb birt branding help maildev proxy gf"
> ```

The oscm-initdb is tightly coupled with the oscm-core and oscm-app. I'd suggest to remove it here. 
___
*[shared/build-base.groovy, line 333 at r1](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/26#-MLr_uZsAq2CbBkW2bs1:-MLr_uZsAq2CbBkW2bs2:b-lpcbmx) ([raw file](https://github.com/servicecatalog/oscm-jenkinsscripts/blob/95122cfa0b3e37663ca917b9441dcb2655124ef0/shared/build-base.groovy#L333)):*
> ```Groovy
>     _buildWebserverImage()
>     _buildBirtImage()
>     _buildInitDBImage()
> ```

initdb should be moved (s.o.)
Is it really needed to clone and compile oscm, documentaion and oscm-app
___
*[shared/build-core.groovy, line 411 at r1](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/26#-MLraTcC8AAoX3nU45G1:-MLraTcC8AAoX3nU45G2:b6miu0d) ([raw file](https://github.com/servicecatalog/oscm-jenkinsscripts/blob/95122cfa0b3e37663ca917b9441dcb2655124ef0/shared/build-core.groovy#L411)):*
> ```Groovy
>     _prepareRestAPIRepository()
>     _prepareApprovalAdapterRepository()
> ```

initDb should be added here

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/26)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @cworf91 and @GoebelL)

___
*[build-core-and-push.groovy, line 89 at r1](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/26#-MLrajKR-FfNfas-CXYX:-MLrajKR-FfNfas-CXYY:b-aec01w) ([raw file](https://github.com/servicecatalog/oscm-jenkinsscripts/blob/95122cfa0b3e37663ca917b9441dcb2655124ef0/build-core-and-push.groovy#L89)):*
> ```Groovy
>     
>     def IMAGES="core app deployer identity"
> ```

and initdb

**Review by GoebelL — COMMENTED** [review]
> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/26)* status: 2 of 7 files reviewed, 4 unresolved discussions (waiting on @cworf91)

**Review by cworf91 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/26)* status: 2 of 7 files reviewed, 4 unresolved discussions (waiting on @GoebelL)

___
*[build-base-and-push.groovy, line 88 at r1](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/26#-MLr_NjZ41MocESJhCoA:-MLvevodBC0Xp-NTjzsQ:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-jenkinsscripts/blob/95122cfa0b3e37663ca917b9441dcb2655124ef0/build-base-and-push.groovy#L88)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

The oscm-initdb is tightly coupled with the oscm-core and oscm-app. I'd suggest to remove it here. 
</blockquote></details>

Done.
___
*[build-core-and-push.groovy, line 89 at r1](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/26#-MLrajKR-FfNfas-CXYX:-MLvexBM7824nvEDnOBY:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-jenkinsscripts/blob/95122cfa0b3e37663ca917b9441dcb2655124ef0/build-core-and-push.groovy#L89)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

and initdb
</blockquote></details>

Done.
___
*[shared/build-base.groovy, line 333 at r1](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/26#-MLr_uZsAq2CbBkW2bs1:-MLvez2M6YsHxDE_LelI:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-jenkinsscripts/blob/95122cfa0b3e37663ca917b9441dcb2655124ef0/shared/build-base.groovy#L333)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

initdb should be moved (s.o.)
Is it really needed to clone and compile oscm, documentaion and oscm-app
</blockquote></details>

Done.
___
*[shared/build-core.groovy, line 411 at r1](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/26#-MLraTcC8AAoX3nU45G1:-MLvf0xD0k-xQ9ZVb-qH:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-jenkinsscripts/blob/95122cfa0b3e37663ca917b9441dcb2655124ef0/shared/build-core.groovy#L411)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

initDb should be added here
</blockquote></details>

Done.

**Review by GoebelL — COMMENTED** [review]
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/26)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @GoebelL)

**Review by GoebelL — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/26)* status: 6 of 7 files reviewed, all discussions resolved

**Review by GoebelL — APPROVED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/26)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
