### PR TITLE
Azure setup with single jenkins agent

### PR DESCRIPTION
**Pull request by kowalczyka**
**Changes in this Pull Request:**
- Azure setup improvements (single jenkins agent, initial pipeline for pull and start job)

**Mandatory checks:**
- [x] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [x] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Copyrights are included 
- [ ] No hard-code values for any sensitive or environment specific settings    
- [ ] Usage changes are documented in readme md form
- [ ] Human readable (e.g. yaml code comments)

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/79)

### CODE REVIEW

**Review by cworf91 — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/79)* status: all files reviewed, 1 unresolved discussion (waiting on @kowalczyka)

___
*[setup/azure/Vagrantfile, line 52 at r1](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/79#-McJIrmO9fFCFkO7z0pf:-McJIrmP2lqjdG1qBkwZ:b-rmgl1u) ([raw file](https://github.com/servicecatalog/oscm-jenkinsscripts/blob/843444b77046fceffe7962dd1e82f249ede83542/setup/azure/Vagrantfile#L52)):*
> ```Ruby
>     jenkins.vm.provision "file", source: "provisioning/jenkins.conf", destination: "/home/vagrant/provisioning/jenkins.conf"
>     jenkins.vm.provision "file", source: "provisioning/plugins.yaml", destination: "/home/vagrant/provisioning/plugins.yaml"
>     jenkins.vm.provision "file", source: "C:/Users/KOWALCZYKA/.ssh/id_rsa", destination: "/home/vagrant/agent_key"
> ```

Can we put this key into version controll or do we have to generate it?

**Review by GoebelL — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/79)* status: all files reviewed, 1 unresolved discussion (waiting on @cworf91)

___
*[setup/azure/Vagrantfile, line 52 at r1](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/79#-McJIrmO9fFCFkO7z0pf:-McTvRaN5dhNt5JBJi-1:blcz9a5) ([raw file](https://github.com/servicecatalog/oscm-jenkinsscripts/blob/843444b77046fceffe7962dd1e82f249ede83542/setup/azure/Vagrantfile#L52)):*
<details><summary><i>Previously, cworf91 (cworf91) wrote…</i></summary><blockquote>

Can we put this key into version controll or do we have to generate it? 
</blockquote></details>

The key is generated eachtime, but nevertheless putting RSA keys in public versions control would be a no go.
Can we use a variable?

**Review by kowalczyka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/79)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @cworf91)

___
*[setup/azure/Vagrantfile, line 52 at r1](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/79#-McJIrmO9fFCFkO7z0pf:-McU6M0-D0sNcLzabhSi:b9g7aec) ([raw file](https://github.com/servicecatalog/oscm-jenkinsscripts/blob/843444b77046fceffe7962dd1e82f249ede83542/setup/azure/Vagrantfile#L52)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

The key is generated eachtime, but nevertheless putting RSA keys in public versions control would be a no go.
Can we use a variable?

</blockquote></details>

Yes, it is done with a variable now

**Review by kowalczyka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/79)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @cworf91)

___
*[setup/azure/Vagrantfile, line 52 at r1](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/79#-McJIrmO9fFCFkO7z0pf:-McU6UB-5nVtFPTU189x:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-jenkinsscripts/blob/843444b77046fceffe7962dd1e82f249ede83542/setup/azure/Vagrantfile#L52)):*
<details><summary><i>Previously, kowalczyka (Arkadiusz Kowalczyk) wrote…</i></summary><blockquote>

Yes, it is done with a variable now
</blockquote></details>

Done.

**Review by cworf91 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/79#-:-McU75wTANpn-Ek95ZHN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kowalczyka)

**Pull request merged**
