### PR TITLE
New oscm-mail related changes

### PR DESCRIPTION
**Pull request by kowalczyka**
**Changes in this Pull Request:**
- all necessary configuration of oscm-mail and maildev containers

**Mandatory checks:**
- [x] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [x] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Copyrights are included 
- [ ] No hard-code values for any sensitive or environment specific settings    
- [ ] Usage changes are documented in readme md form
- [ ] Human readable (e.g. yaml code comments)

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/55)

### CODE REVIEW

**Review by GoebelL — APPROVED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/55)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cworf91)

**Review by cworf91 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/55#-:-MZH_99uE_bj36B8dQhM:bnfp4nl)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @kowalczyka)

**Review by cworf91 — APPROVED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/55)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kowalczyka)

**Review by GoebelL — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/55)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kowalczyka)

**Review by GoebelL — COMMENTED** [review]
> Reviewed 5 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/55)* status: 6 of 8 files reviewed, all discussions resolved (waiting on @kowalczyka)

**Review by cworf91 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/55#-:-McOLiUA9ZMreeH5E9UI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kowalczyka)

**Pull request merged**
