### PR TITLE
OSCM related pipelines for local setup

### LINKED ISSUE #66: Adapt pipeline scripts for new playbook version
**Summary**
Adapt pipeline scripts for new playbook version

**Details**
 - autostarting of docker service
 - other cleaned setup changes

**Acceptance criteria**
- [ ] Pipeline scripts are updated and running well

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by kowalczyka**
**Changes in this Pull Request:**
- local setup for Jenkins extended with other jobs (daily build, tests related)

**Mandatory checks:**
- [x] Branch is up to date (latest changes were fetched from the upstream branch before creating this PR)
- [x] Changes were tested manually
- [ ] Java code changes are unit tested
- [ ] Webtests are successful

**To be checked by the reviewer:**
- [ ] Copyrights are included 
- [ ] No hard-code values for any sensitive or environment specific settings    
- [ ] Usage changes are documented in readme md form
- [ ] Human readable (e.g. yaml code comments)

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/71)

### CODE REVIEW

**Review by cworf91 — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/71#-:-MabvJ11E4oVu-4PVO-Q:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @kowalczyka)

___
*[setup/local/provisioning/jobs/OSCM_Tests_IT_OIDC/config.xml, line 158 at r1](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/71#-Mabv-bQ0HoByPASwSU0:-Mabv-bQ0HoByPASwSU1:b-djofvu) ([raw file](https://github.com/servicecatalog/oscm-jenkinsscripts/blob/97de2ceea057a53a71a4fc6bee263d94258de33f/setup/local/provisioning/jobs/OSCM_Tests_IT_OIDC/config.xml#L158)):*
> ```XML
>           <name>CLIENT_ID</name>
>           <description>The client ID of the Azure application for test purpose.</description>
>           <defaultValue>ef29aa22-369b-424f-9c72-6800fb24239d</defaultValue>
> ```

Maybe we should´t put this in source. What do you think?
___
*[setup/local/provisioning/jobs/OSCM_Tests_WS_OIDC/config.xml, line 153 at r1](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/71#-MabvF3Y6gXOdojzcgM2:-MabvF3Y6gXOdojzcgM3:bb73xfv) ([raw file](https://github.com/servicecatalog/oscm-jenkinsscripts/blob/97de2ceea057a53a71a4fc6bee263d94258de33f/setup/local/provisioning/jobs/OSCM_Tests_WS_OIDC/config.xml#L153)):*
> ```XML
>           <name>CLIENT_ID</name>
>           <description>The client ID of the Azure application for test purpose.</description>
>           <defaultValue>ef29aa22-369b-424f-9c72-6800fb24239d</defaultValue>
> ```

Same

**Review by kowalczyka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/71)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @cworf91)

___
*[setup/local/provisioning/jobs/OSCM_Tests_IT_OIDC/config.xml, line 158 at r1](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/71#-Mabv-bQ0HoByPASwSU0:-MabyMeYAC3mmr_wTDUE:ba3dfob) ([raw file](https://github.com/servicecatalog/oscm-jenkinsscripts/blob/97de2ceea057a53a71a4fc6bee263d94258de33f/setup/local/provisioning/jobs/OSCM_Tests_IT_OIDC/config.xml#L158)):*
<details><summary><i>Previously, cworf91 (cworf91) wrote…</i></summary><blockquote>

Maybe we should´t put this in source. What do you think?
</blockquote></details>

Removed
___
*[setup/local/provisioning/jobs/OSCM_Tests_WS_OIDC/config.xml, line 153 at r1](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/71#-MabvF3Y6gXOdojzcgM2:-MabyQey-y5LGuKQccYj:ba3dfob) ([raw file](https://github.com/servicecatalog/oscm-jenkinsscripts/blob/97de2ceea057a53a71a4fc6bee263d94258de33f/setup/local/provisioning/jobs/OSCM_Tests_WS_OIDC/config.xml#L153)):*
<details><summary><i>Previously, cworf91 (cworf91) wrote…</i></summary><blockquote>

Same
</blockquote></details>

Removed

**Review by kowalczyka — COMMENTED** [review]
> Dismissed @cworf91 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/71)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @cworf91)

**Review by kowalczyka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/71)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @cworf91)

___
*[setup/local/provisioning/jobs/OSCM_Tests_WS_OIDC/config.xml, line 153 at r1](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/71#-MabvF3Y6gXOdojzcgM2:-Mabyl060v_MuI0BenLi:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-jenkinsscripts/blob/97de2ceea057a53a71a4fc6bee263d94258de33f/setup/local/provisioning/jobs/OSCM_Tests_WS_OIDC/config.xml#L153)):*
<details><summary><i>Previously, kowalczyka (Arkadiusz Kowalczyk) wrote…</i></summary><blockquote>

Removed
</blockquote></details>

Done.

**Review by cworf91 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-jenkinsscripts/71#-:-MabzDel6-lSkjml5z-F:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kowalczyka)

**Pull request merged**
